# -*- encoding: utf-8 -*-
# ISO 639-2 lookup
import util

# https://pt.wikipedia.org/w/index.php?title=ISO_639&oldid=42409922
lattesToISO639 = {
    'lingua afar': 'aar',
    'lingua abecasia': 'abk',
    'achem': 'ace',
    'acholi': 'ach',
    'adangme': 'ada',
    'adyghe': 'ady',
    'linguas afro-asiaticas': 'afa',
    'afrihili': 'afh',
    'africander': 'afr',
    'aino': 'ain',
    'akan': 'aka',
    'acadio': 'akk',
    'aleute': 'ale',
    'algonquina': 'alg',
    'altaico meridional': 'alt',
    'amarico': 'amh',
    'ingles antigo': 'ang',
    'apache': 'apa',
    'arabe': 'ara',
    'aramaico': 'arc',
    'aragones': 'arg',
    'araucano': 'arn',
    'arapaho': 'arp',
    'linguas artificiais': 'art',
    'araucano': 'arw',
    'assames': 'asm',
    'asturiano': 'ast',
    'athapascans': 'ath',
    'linguas australianas': 'aus',
    'avarico': 'ava',
    'avestico': 'ave',
    'awadhi': 'awa',
    'aimara': 'aym',
    'azerbaijano': 'aze',
    'banda': 'bad',
    'linguas bamileque': 'bai',
    'baxequir': 'bak',
    'baluchi': 'bal',
    'bambara': 'bam',
    'balines': 'ban',
    'basa': 'bas',
    'linguas balticas': 'bat',
    'beja': 'bej',
    'bielorusso': 'bel',
    'bemba': 'bem',
    'bengali': 'ben',
    'linguas berberes': 'ber',
    'bhojpuri': 'bho',
    'biari': 'bih',
    'bikol': 'bik',
    'bini': 'bin',
    'bislama': 'bis',
    'siksika': 'bla',
    'linguas bantas': 'bnt',
    'tibetano': 'tib',
    'bosnio': 'bos',
    'braj': 'bra',
    'bretao': 'bre',
    'bataque (indonesia)': 'btk',
    'buriat': 'bua',
    'bugines': 'bug',
    'bulgaro': 'bul',
    'blin': 'byn',
    'caddo': 'cad',
    'linguas indigenas': 'cai',
    'caribe': 'car',
    'catalao': 'cat',
    'caucaso': 'cau',
    'cebuano': 'ceb',
    'celtico': 'cel',
    'tcheco': 'cze',
    'chamorro': 'cha',
    'chibcha': 'chb',
    'tchecheno': 'che',
    'chagatai': 'chg',
    'chuukes': 'chk',
    'mari': 'chm',
    'jargao chinook': 'chn',
    'choctaw': 'cho',
    'chipewyan': 'chp',
    'cherokee': 'chr',
    'eslavo eclesiastico': 'chu',
    'tchuvache': 'chv',
    'cheyenne': 'chy',
    'chamic': 'cmc',
    'copto': 'cop',
    'cornico': 'cor',
    'corso': 'cos',
    'cree': 'cre',
    'tartaro da crimeia': 'crh',
    'creole': 'crp',
    'casubio': 'csb',
    'cushitico': 'cus',
    'gales': 'wel',
    'dakota': 'dak',
    'dinamarques': 'dan',
    'darginico': 'dar',
    'dayak': 'day',
    'delaware': 'del',
    'slave (athapascano)': 'den',
    'alemao': 'ger',
    'dogrib': 'dgr',
    'dinka': 'din',
    'divehi': 'div',
    'dogri': 'doi',
    'dravidiano': 'dra',
    'sorabio baixo': 'dsb',
    'duala': 'dua',
    'holandes medio': 'dum',
    'dyula': 'dyu',
    'dzongkha': 'dzo',
    'efik': 'efi',
    'egipcio antigo': 'egy',
    'ekajuk': 'eka',
    'grego moderno': 'gre',
    'elamita': 'elx',
    'ingles': 'eng',
    'ingles medio': 'enm',
    'esperanto': 'epo',
    'estoniano': 'est',
    'basco': 'baq',
    'ewe': 'ewe',
    'ewondo': 'ewo',
    'fang': 'fan',
    'feroes': 'fao',
    'persa': 'per',
    'fanti': 'fat',
    'fidjiano': 'fij',
    'filipino': 'fil',
    'finlandes': 'fin',
    'fino-ugrico': 'fiu',
    'fon': 'fon',
    'frances': 'fre',
    'frances medio': 'frm',
    'frances antigo': 'fro',
    'frisao': 'fry',
    'fula': 'ful',
    'friuliano': 'fur',
    'ga': 'gaa',
    'gayo': 'gay',
    'gbaya': 'gba',
    'linguas germanicas': 'gem',
    "ge'ez": 'gez',
    'gilbertes': 'gil',
    'gaelico escoces': 'gla',
    'irlandes': 'gle',
    'galego': 'glg',
    'manes': 'glv',
    'alto-alemao medio': 'gmh',
    'alto-alemao antigo': 'goh',
    'gondi': 'gon',
    'gorontalo': 'gor',
    'gotico': 'got',
    'grebo': 'grb',
    'grego antigo': 'grc',
    'guarani': 'grn',
    'gujarati': 'guj',
    'gwichin': 'gwi',
    'haida': 'hai',
    'crioulo haitiano': 'hat',
    'hauca': 'hau',
    'havaiano': 'haw',
    'hebraico': 'heb',
    'herero': 'her',
    'hiligaynon': 'hil',
    'himachali': 'him',
    'hindi': 'hin',
    'hitita': 'hit',
    'hmong': 'hmn',
    'hiri motu': 'hmo',
    'croata': 'scr',
    'sorabio alto': 'hsb',
    'hungaro': 'hun',
    'hupa': 'hup',
    'armenio': 'arm',
    'iban': 'iba',
    'ibo': 'ibo',
    'ido': 'ido',
    'yi': 'iii',
    'ijo': 'ijo',
    'inuktitut': 'iku',
    'interlingua': 'ile',
    'ilocano': 'ilo',
    'interlingua': 'ina',
    'indico': 'inc',
    'indonesio': 'ind',
    'indo-europeu': 'ine',
    'ingush': 'inh',
    'inupiaq': 'ipk',
    'iraniano': 'ira',
    'iroquoiano': 'iro',
    'islandes': 'ice',
    'italiano': 'ita',
    'javanes': 'jav',
    'lojban': 'jbo',
    'japones': 'jpn',
    'judeu-persa': 'jpr',
    'judeu-arabe': 'jrb',
    'kara-kalpak': 'kaa',
    'kabyle': 'kab',
    'kachin': 'kac',
    'groenlandes': 'kal',
    'kamba': 'kam',
    'canara': 'kan',
    'karen': 'kar',
    'cachemir': 'kas',
    'georgiano': 'geo',
    'kanuri': 'kau',
    'kawi': 'kaw',
    'cazaque': 'kaz',
    'cabardiano': 'kbd',
    'khasi': 'kha',
    'khoisano': 'khi',
    'khmer': 'khm',
    'khotanes': 'kho',
    'kikuyu': 'kik',
    'quiniaruanda': 'kin',
    'quirguiz': 'kir',
    'quimbundu': 'kmb',
    'concani': 'kok',
    'komi': 'kom',
    'kongo': 'kon',
    'coreano': 'kor',
    'kosraeano': 'kos',
    'kpelle': 'kpe',
    'karachay-balkar': 'krc',
    'carelio': 'krl',
    'kru': 'kro',
    'kurukh': 'kru',
    'oshikwanyama': 'kua',
    'kumyk': 'kum',
    'curdo': 'kur',
    'kutenai': 'kut',
    'ladino': 'lad',
    'lahnda': 'lah',
    'lamba': 'lam',
    'laociano': 'lao',
    'latim': 'lat',
    'letao': 'lav',
    'lezgui': 'lez',
    'limburgues': 'lim',
    'lingala': 'lin',
    'lituano': 'lit',
    'mongo': 'lol',
    'lozi': 'loz',
    'luxemburgues': 'ltz',
    'luba-lulua': 'lua',
    'luba-katanga': 'lub',
    'luganda': 'lug',
    'luisenho': 'lui',
    'lunda': 'lun',
    'luo': 'luo',
    'lushai': 'lus',
    'madhures': 'mad',
    'magahi': 'mag',
    'marshalles': 'mah',
    'maithili': 'mai',
    'makasar': 'mak',
    'malaiala': 'mal',
    'mandinga': 'man',
    'austronesio': 'map',
    'marata': 'mar',
    'masai': 'mas',
    'moksha': 'mdf',
    'mandar': 'mdr',
    'mende': 'men',
    'irlandes medio': 'mga',
    'micmac': 'mic',
    'minangkabau': 'min',
    'macedonio': 'mac',
    'mon-khmer': 'mkh',
    'malgaxe': 'mlg',
    'maltes': 'mlt',
    'manchu': 'mnc',
    'manipuri': 'mni',
    'manobo': 'mno',
    'mohawk': 'moh',
    'moldavo': 'mol',
    'mongol': 'mon',
    'mossi': 'mos',
    'maori': 'mao',
    'malaio': 'may',
    'munda': 'mun',
    'creek': 'mus',
    'mirandes': 'mwl',
    'marwari': 'mwr',
    'birmanes': 'bur',
    'maia': 'myn',
    'erzya': 'myv',
    'nahuatl': 'nah',
    'amerindio': 'nai',
    'napolitano': 'nap',
    'nauruano': 'nau',
    'navajo': 'nav',
    'ndebele do sul': 'nbl',
    'ndebele do norte': 'nde',
    'ndonga': 'ndo',
    'baixo saxao': 'nds',
    'nepali': 'nep',
    'newari': 'new',
    'nias': 'nia',
    'niger-cordofanio': 'nic',
    'niueano': 'niu',
    'holandes': 'dut',
    'novo noruegues': 'nno',
    'bokmal noruegues': 'nob',
    'nogai': 'nog',
    'noruegues antigo': 'non',
    'noruegues': 'nor',
    'sesotho do norte': 'nso',
    'nubio': 'nub',
    'newari classico': 'nwc',
    'nianja': 'nya',
    'nyamwezi': 'nym',
    'nyankole': 'nyn',
    'nyoro': 'nyo',
    'nzima': 'nzi',
    'occitano': 'oci',
    'chippewa': 'oji',
    'oria': 'ori',
    'oromo': 'orm',
    'osage': 'osa',
    'oseto': 'oss',
    'turco otomano': 'ota',
    'otomiano': 'oto',
    'papuano': 'paa',
    'pangasinan': 'pag',
    'pahlavi': 'pal',
    'pampanga': 'pam',
    'panjabi': 'pan',
    'papiamento': 'pap',
    'palauano': 'pau',
    'persa antigo': 'peo',
    'filipina': 'phi',
    'fenicio': 'phn',
    'pali': 'pli',
    'polaco': 'pol',
    'ponpeiano': 'pon',
    'portugues': 'por',
    'prakrit': 'pra',
    'provencal antigo': 'pro',
    'pachto': 'pus',
    'quichua': 'que',
    'rajasthani': 'raj',
    'rapanui': 'rap',
    'rarotonga': 'rar',
    'romance': 'roa',
    'reto-romano': 'roh',
    'romani': 'rom',
    'romeno': 'rum',
    'kirundi': 'run',
    'russo': 'rus',
    'sandawe': 'sad',
    'sango': 'sag',
    'yakut': 'sah',
    'linguas indigenas da america do sul': 'sai',
    'salishano': 'sal',
    'aramaico samaritano': 'sam',
    'sanscrito': 'san',
    'sasaque': 'sas',
    'santali': 'sat',
    'siciliano': 'scn',
    'escoces': 'sco',
    'selkup': 'sel',
    'linguas semiticas': 'sem',
    'irlandes antigo': 'sga',
    'linguas gestuais': 'sgn',
    'shan': 'shn',
    'sidamo': 'sid',
    'cingales': 'sin',
    'sioux': 'sio',
    'linguas sino-tibetanas': 'sit',
    'linguas eslavas': 'sla',
    'eslovaco': 'slo',
    'esloveno': 'slv',
    'sami': 'sma',
    'sami': 'sme',
    'sami': 'smi',
    'sami': 'smj',
    'sami': 'smn',
    'samoano': 'smo',
    'sami': 'sms',
    'chona': 'sna',
    'sindi': 'snd',
    'soninke': 'snk',
    'sogdiano': 'sog',
    'somali': 'som',
    'songhai': 'son',
    'soto do sul': 'sot',
    'espanhol': 'spa',
    'castelhano': 'spa',
    'albanes': 'alb',
    'sardo': 'srd',
    'servio': 'scc',
    'serer': 'srr',
    'nilo-saharano': 'ssa',
    'suazi': 'ssw',
    'sukuma': 'suk',
    'sundanes': 'sun',
    'susu': 'sus',
    'sumerio': 'sux',
    'suaili': 'swa',
    'sueco': 'swe',
    'siriaco': 'syr',
    'taitiano': 'tah',
    'linguas tailandesas': 'tai',
    'tamil': 'tam',
    'tartaro': 'tat',
    'telugu': 'tel',
    'timne': 'tem',
    'tereno': 'ter',
    'tetum': 'tet',
    'tajique': 'tgk',
    'tagalo': 'tgl',
    'tailandes': 'tha',
    'tigre': 'tig',
    'tigrinia': 'tir',
    'tiv': 'tiv',
    'tokelau': 'tkl',
    'klingon': 'tlh',
    'tlingit': 'tli',
    'tamasheque': 'tmh',
    'tonga': 'tog',
    'tonganes': 'ton',
    'tok pisin': 'tpi',
    'tsimshian': 'tsi',
    'tswana': 'tsn',
    'tsonga': 'tso',
    'turcomano': 'tuk',
    'tumbuka': 'tum',
    'tupi': 'tup',
    'turco': 'tur',
    'linguas altaicas': 'tut',
    'tuvaluano': 'tvl',
    'twi': 'twi',
    'tuviniano': 'tyv',
    'udmurt': 'udm',
    'ugaritico': 'uga',
    'uigur': 'uig',
    'ucraniano': 'ukr',
    'umbundu': 'umb',
    'urdu': 'urd',
    'uzbeque': 'uzb',
    'vai': 'vai',
    'venda': 'ven',
    'vietnamita': 'vie',
    'volapuque': 'vol',
    'votico': 'vot',
    'wakashano': 'wak',
    'walamo': 'wal',
    'waray-waray': 'war',
    'washo': 'was',
    'gales': 'wel',
    'linguas sorabias': 'wen',
    'valao': 'wln',
    'wolof': 'wol',
    'calmuc': 'xal',
    'xhosa': 'xho',
    'yao': 'yao',
    'yapes': 'yap',
    'iidiche': 'yid',
    'ioruba': 'yor',
    'yupique': 'ypk',
    'zapoteca': 'zap',
    'zenaga': 'zen',
    'zhuang': 'zha',
    'chines': 'chi',
    'zande': 'znd',
    'zulu': 'zul',
    'zunhi': 'zun',
}

def lookup(idiomaLattes):
    return lattesToISO639.get(util.norm(idiomaLattes))

if __name__ == '__main__':
    # Verifica consistência da tabela
    import re
    for k, v in lattesToISO639.iteritems():
        assert(k == util.norm(k))         # sem acentos
        assert(re.match('^[a-z]{3}$', v)) # 3 letras
